name: HGLaborBingo
version: 1.0.0
main: de.hglabor.Bingo
api-version: 1.16
depend: [ Chunky ]
commands:
  bingo:
    description: See which Items you have to find
    aliases: b
  start:
    description: Start the Game.
  settings:
    description: Edit the Bingo Settings.
  top:
    description: Teleport you to the highest y coordinate at your location.
  teams:
    description: Choose your team!
  backpack:
    description: Open your team-backpack!
    aliases: bp
  tc:
    description: Communicate with your team members!
    aliases: teamchat
