name: HGLaborBingo
version: 1.0.0
main: de.hglabor.Bingo
api-version: 1.16
commands:
  bingo:
    description: See which Items you have to find
    usage: /bingo
  start:
    description: Start the Game
    usage: /start
  settings:
    description: Edit the Bingo Settings
    usage: /settings